### ISSUE TITLE
SQLiteConstraintException

### ISSUE THREAD

**Issue by ScottEAdams** [pardom-zz/ActiveAndroid#127]
When doing

```
SQLiteUtils.execSql("DELETE FROM Devices");
```

or

```
new Delete().from(Device.class).execute();
```

It works fine some of the time but then out of nowhere it throws

```
android.database.sqlite.SQLiteConstraintException: foreign key constraint failed (code 19)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:858)
            at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1665)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1594)
            at com.activeandroid.util.SQLiteUtils.execSql(Unknown Source)
```

I have a foreign key on the table that I have tried setting

onDelete = Column.ForeignKeyAction.SET_NULL

and

onDelete = Column.ForeignKeyAction.CASCADE

and without any onDelete and the same problem arises. Any ideas?

**Comment by leonardoxh** [comment]
Can you post your Device model and the related models?

**Comment by ScottEAdams** [comment]
It seemed to be happening on all devices I tried it on - 
Sony Ericsson LT18i (Phone) Android 4.0.4
Semc Xperia Arc S (Phone)   Android 4.2.2
Samsung GT-I9100 (Phone)    Android 4.1.2
HTC Wildfire S A510e (Phone)    Android 2.3.5

```
@Table(name = "Devices")
public class Device extends Model
{
    @Column(name = "device_id", unique = true, onUniqueConflict = Column.ConflictAction.REPLACE)
    public int device_id;

    @Column(name = "resource_uri")
    public String resource_uri;

    @Column(name = "vehicle", onDelete = Column.ForeignKeyAction.SET_NULL) <- have tried this with CASCADE also
    public Vehicle vehicle;
}

@Table(name = "Vehicles")
public class Vehicle extends Model
{
    @Column(name = "vehicle_id", unique = true, onUniqueConflict = Column.ConflictAction.REPLACE)
    public int vehicle_id;

    @Column(name = "resource_uri")
    public String resource_uri;
}
```

I got so frustrated with it that I ended up removing all relations :(

**Comment by divjotnanda** [comment]
Facing the same issue with my application also.
Can anyone help...?

**Comment by matthew-reilly** [comment]
This still seems to be an issue. If anyone figured this out, some help would be appreciated.

**Comment by davidgoli** [comment]
+1 I'm seeing this issue as well, exactly as reported. It seems after deleting the app from the device, the first install is fine, but subsequent installs consistently fail. This is a major bug.

**Comment by lamsaitat** [comment]
Encountering the exact same problem as @davidgoli .  Have added onDelete = Column.ForeignKeyAction.CASCADE as others have suggested from google search but didn't resolve the problem.

**Comment by NHamdi** [comment]
Encountered this problem today, if anyone still have the "issue", you just have to delete all relations before, in this case, you have to call Vehicles.deleteall(), before  Devices.deleteAll().

**Comment by lamsaitat** [comment]
I managed to solve my problem at the end.  With my case it was at update that caused the exception.  Adding onUpdate = CASCADE solved it.

**Comment by twobitlabs** [comment]
+1 I'm seeing this problem too. Deleting the dependent records first resolves it, adding `onDelete = Column.ForeignKeyAction.CASCADE` does not.

**Comment by twobitlabs** [comment]
Browsing through the ActiveAndroid code, it appears that the `onDelete` annotation is only read when the column is created. If the column already exists in your installation, the ON DELETE action will not be added. You have to create a migration to add it.

**Comment by fcgregorio** [comment]
Just to be sure, is `onDelete = Column.ForeignKeyAction.CASCADE` already working even with uninstalling then installing app? I'm having difficulty making it work. Right now I'm just deleting the dependent records first then I delete the referenced records.

**Comment by twobitlabs** [comment]
Yes, for me it worked to uninstall the app, as the tables get re-created with the ON DELETE action on the column.

**Comment by lamsaitat** [comment]
yes you do need to purge existing table (or update the table with the right
migration statement) because on delete and on update is part of the schema.

**Comment by schlamar** [comment]
Just stumbled about this issue per accident. There is a bug in SQLite regarding Foreign Keys which occurs in 3.6.21 and is fixed at least since 3.8.1. This might be the cause of this bug. More details can be found here: http://bugs.python.org/issue19450

**Comment by TifonT** [comment]
I have a similar problem and I do not understand how to solve it.
Class Store
```
@Table(name = "Stores")
public class Store extends Model implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 7460944071388957765L;

	@Column
	@SerializedName("_id")
	private String storeId;
	@Column
	private String name;
	@Column
	private String address;
	@Column
	private String phone;
	@Column
	private String fax;
	@Column
	private String email;
	@Column
	private Logo logo;
	@Column
	private GPS gps;
	@Column
	private boolean isFavorite;
	private double distance;
}
```
At first everything is fine, but after a while begins to fall in error
```
new Delete().from(Store.class).where("isFavorite = ?", false).execute();
```
```
android.database.sqlite.SQLiteConstraintException: foreign key constraint failed (code 19)
```

**Comment by ImMathanR** [comment]
Anyone figured out a way around this?
