### ISSUE TITLE
How to disable scanning for model

### ISSUE THREAD

**Issue by TomaszZGor** [pardom-zz/ActiveAndroid#228]
I would like to define my model in AndroidManifest.xml file using AA_MODEL tag and disable auto search. Because currently I get errors similar to:     

```
Couldn't create class.
    java.lang.ClassNotFoundException: android.support.v4.print.PrintHelperKitkat$1
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:204)
            at com.activeandroid.ModelInfo.scanForModelClasses(Unknown Source)
            at com.activeandroid.ModelInfo.scanForModel(Unknown Source)
            at com.activeandroid.ModelInfo.<init>(Unknown Source)
            at com.activeandroid.Cache.initialize(Unknown Source)
            at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
            at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
            at com.comapny.myApp.app.MyAppApplication.onCreate(Unknown Source)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
            at android.app.ActivityThread.access$1400(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)
```

How to do it properly ? Can you give me example of well defined AA_MODEL tag ?

**Comment by ibrahimpenekli** [comment]
Example;

``` xml
<meta-data
                android:name="AA_MODELS"
                android:value="your.package.ModelA,your.package.ModelB,your.package.ModelC"/>
```

You can also set models and type serializers via Configuration class;

``` java
ActiveAndroid.initialize(new Configuration.Builder(context)
                .addModelClass(ModelA.class)
                .addModelClass(ModelB.class)
                .addModelClass(ModelC.class)
                .addTypeSerializer(MyTypeSerializerA.class)
                .addTypeSerializer(MyTypeSerializerB.class)
                .create());
```

**Comment by TomaszZGor** [comment]
@ibrahimpenekli  Thank you for help! It should be added to documentation. Now i see that my scanning is disabled without this code... I don't know how it happen...

**Comment by GJson** [comment]
you should read the class " Configuration.java"  or  this page http://blog.csdn.net/zhuangyalei/article/details/52093857  
maybe help you
