### ISSUE TITLE
Crash in ModelInfo.scanForModelClasses() on certain Motorola devices

### ISSUE THREAD

**Issue by MigrantP** [pardom-zz/ActiveAndroid#231]
We ran into a mysterious startup crash in the wild that only happened on certain Motorola devices:
- Moto X (ghost) - 4.4
- Droid Ultra (obake) - 4.4
- DROID RAZR HD (vanquish) - 4.4
- XT897 (asanti_c) - 4.1

They all had a similar stack trace as seen below. We were able to work around the problem by supplying a configuration with our model class (there's just one) instead of letting it scan.

The problem _may_ be related to ProGuard but we were never able to tell for sure. We never had a problem like this with any other devices. We do not have any of those Motorola devices in house and had to rely on beta testers trying out builds for us.

```
java.lang.RuntimeException: Unable to create application com.myCompany.MyApp: java.lang.NullPointerException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4428)
at android.app.ActivityThread.access$1500(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5102)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.activeandroid.ModelInfo.scanForModelClasses(Unknown Source)
at com.activeandroid.ModelInfo.scanForModel(Unknown Source)
at com.activeandroid.ModelInfo.<init>(Unknown Source)
at com.activeandroid.Cache.initialize(Unknown Source)
at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
at com.activeandroid.app.Application.onCreate(Unknown Source)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1030)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
... 10 more
```

**Comment by tomblenz** [comment]
Same error, here - motorola devices only.  NPE happens at line 158 of ModelInfo.scanForModelClasses.

**Comment by ghost** [comment]
Has any of you found a solution/workaround for this yet?

**Comment by jlhonora** [comment]
A simple solution is to add your AA model classes in the AA_MODELS section in the manifest. More info here https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model#speeding-up-application-startup
