### ISSUE TITLE
Nothing saves when using in memory database (no name)

### ISSUE THREAD

**Issue by loeschg** [pardom-zz/ActiveAndroid#241]
I'm attempting to create an in memory database using ActiveAndroid in order to do unit testing (need to reset the database for each run). I have the following code executed in the `onCreate` of my TestApplication object:

``` java
Configuration config = new Configuration.Builder(this)
                .setDatabaseName(null) // This should create an in memory db, right?
                .setDatabaseVersion(getResources().getInteger(R.integer.database_version))
                .create();
ActiveAndroid.initialize(config);
```

When I do this, nothing seems to save in the database. Am I initializing this incorrectly? Any help would be fantastic.

**Comment by loeschg** [comment]
Yeah, the insert into the table is failing. I get a return value of `-1` when calling `save()`

**Comment by loeschg** [comment]
Replacing L155 in Model.java 

```
mId = db.insert(mTableInfo.getTableName(), null, values);
```

with 

```
mId = db.insertOrThrow(mTableInfo.getTableName(), null, values);
```

led me to the following stacktrace in my Robolectric tests:

```
android.database.sqlite.SQLiteException: Cannot execute for last inserted row ID, base error code: 10
    at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:48)
    at org.robolectric.shadows.ShadowSQLiteConnection.access$500(ShadowSQLiteConnection.java:26)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:436)
    at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecuteForLastInsertedRowId(ShadowSQLiteConnection.java:239)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
    at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1365)
    at com.activeandroid.Model.save(Model.java:155)
    at com.app.search.fragments.SavedCategoryListFragmentTest.testGenerateCategoryRowsOneFavorite(SavedCategoryListFragmentTest.java:60)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.almworks.sqlite4java.SQLiteException: [1802] DB[1] step() [INSERT INTO company(synced,medium_image_url,review_count,location,large_image_url,category_context,lng,vendor_id,small_image_url,booked_ordering,booked,name,review_score,faqs,Id,saved_ordering,leads_enabled,lat) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]DB[1][C] [disk I/O error]
    at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
    at com.almworks.sqlite4java.SQLiteConnection$BaseController.throwResult(SQLiteConnection.java:1562)
    at com.almworks.sqlite4java.SQLiteStatement.stepResult(SQLiteStatement.java:1231)
    at com.almworks.sqlite4java.SQLiteStatement.step(SQLiteStatement.java:302)
    at com.almworks.sqlite4java.SQLiteStatement.stepThrough(SQLiteStatement.java:316)
    at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:243)
    at org.robolectric.shadows.ShadowSQLiteConnection$14.call(ShadowSQLiteConnection.java:239)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:422)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:416)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
```

**Comment by loeschg** [comment]
It was an operator error. I forgot to call `ActiveAndroid.dispose()` in my cleanup method in my test class.
