### ISSUE TITLE
ActiveAndroid dispose and initialize throws re-init exception

### ISSUE THREAD

**Issue by thuss** [pardom-zz/ActiveAndroid#242]
When a user logs out I dispose ActiveAndroid, drop the database, and then call initialize:

```
        ActiveAndroid.dispose();
        deleteDatabase(databaseName);
        ActiveAndroid.initialize(this);
```

However sometimes I get the following exception on the call to initialize and was wondering if anyone had any suggestions? We're using ActiveAndroid and Retrofit http library but I'm not sure why ActiveAndroid would be trying to do anything with a Retrofit class:

V/ActiveAndroid( 3232): ActiveAndroid disposed. Call initialize to use library.
I/art     ( 3232): Rejecting re-init on previously-failed class java.lang.Class<retrofit.RxSupport$1>
D/AndroidRuntime( 3232): Shutting down VM
E/AndroidRuntime( 3232): FATAL EXCEPTION: main
E/AndroidRuntime( 3232): Process: com.breezeworks, PID: 3232
E/AndroidRuntime( 3232): java.lang.NoClassDefFoundError: retrofit.RxSupport$1
E/AndroidRuntime( 3232):     at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 3232):     at java.lang.Class.forName(Class.java:305)
E/AndroidRuntime( 3232):     at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
E/AndroidRuntime( 3232):     at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
E/AndroidRuntime( 3232):     at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
E/AndroidRuntime( 3232):     at com.activeandroid.Cache.initialize(Cache.java:66)
E/AndroidRuntime( 3232):     at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
E/AndroidRuntime( 3232):     at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
E/AndroidRuntime( 3232):     at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
E/AndroidRuntime( 3232):     at com.breezeworks.application.BreezeApplication.deleteDatabase(BreezeApplication.java:126)

**Comment by thuss** [comment]
These stackoverflow users seem to be running into similar issues with scanForModelClasses:

http://stackoverflow.com/questions/23907037/how-to-disable-scanning-for-model-in-activeandroid
http://stackoverflow.com/questions/24010996/activeandroid-app-autocloses-when-run-on-gingerbread

**Comment by thuss** [comment]
In our case the class retrofit.RxSupport imports some classes from another jar (netflix rx java) that was missing from our classpath. It didn't cause any problems except with ActiveAndroid. I think because we weren't using the rx java features of retrofit. Importing rx java into our classpath seemed to resolve the issue so I'm going to close this.
