### ISSUE TITLE
ContentProvider in Another Process

### ISSUE THREAD

**Issue by ibrahimpenekli** [pardom-zz/ActiveAndroid#264]
I have content provider like this:

``` xml
<provider
                android:authorities="com.example.blabla"
                android:exported="true"
                android:multiprocess="true"
                android:name="com.activeandroid.content.ContentProvider"/>
```

When I call this in the another process:

``` java
ContentValues values = new ContentValues();
values.put.....

ContentProviderClient client = contentResolver.acquireContentProviderClient("com.example.blabla");
client.insert(ContentProvider.createUri(ExampleModel.class, null), values);
```

Throws an exception;

``` java
java.lang.NullPointerException
            at com.activeandroid.Cache.getTableName(Cache.java:156)
            at com.activeandroid.content.ContentProvider.createUri(ContentProvider.java:151)
          ...
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ibrahimpenekli** [comment]
I've figured out finally.

ContentProvider lives in Process A (and its all resources like Cache, TableInfos etc)

ContentProvider.createUri() is a static method that tries to find TableInfos in another Process. It fails naturally.
I've created another and add a static method

``` java
public class CustomContentProvider extends ContentProvider {
    public static Uri createUri(String tableName, Long id) {
    ...
    }
}
```

that creates Uri from table name.

**Comment by SunnyLy** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
