### ISSUE TITLE
ActiveAndroid across multiple processes

### ISSUE THREAD

**Issue by stabib** [pardom-zz/ActiveAndroid#311]
I have two processes, one is my main app, and the other is a SyncAdapter that runs in the 'sync' process. Both of these processes are writing to the database, and I end up getting a database locked exception (stack trace below). What's the best way to handle this situation? Is there a way to check if the database is locked before starting a transaction?

`<12-05 18:06:35.249: E/AndroidRuntime(25298): FATAL EXCEPTION: SyncAdapterThread-1
12-05 18:06:35.249: E/AndroidRuntime(25298): Process: com.example.test.prod:sync, PID: 25298
12-05 18:06:35.249: E/AndroidRuntime(25298): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at com.activeandroid.ActiveAndroid.beginTransaction(ActiveAndroid.java:64)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at com.example.contacts.ContactSyncAdapter.onPerformSync(ContactSyncAdapter.java:33)
12-05 18:06:35.249: E/AndroidRuntime(25298):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)>`

**Comment by jlhonora** [comment]
I have the same setup, and I use the following to check if the db is locked:

```
if (ActiveAndroid.inTransaction() || ActiveAndroid.getDatabase().isDbLockedByCurrentThread()) {
    return;
}
```

Besides:
- Try to make transactions as short as possible
- I use `Update()` instead of `save()` if I want to save a few columns, seems to be faster.

Note that there might be a much better way, I'm not sure if this is the best way to handle this.

**Comment by stabib** [comment]
@jlhonora I ended up using FileLocks to lock a file shared across two processes, code below. Also, thanks for the tips! I'll take a look at them.

``` java
try {
            // Get a file channel for the file
            File file = new File(LOCK_FILE);
            FileChannel channel = new RandomAccessFile(file, "rw").getChannel();

            // Use the file channel to create a lock on the file.
            // This method blocks until it can retrieve the lock.
            FileLock lock = channel.lock();
            ActiveAndroid.beginTransaction();
            try{
                //do something
                ActiveAndroid.setTransactionSuccessful();
            }finally{
                ActiveAndroid.endTransaction();
            }

            // Release the lock
            lock.release();

            // Close the file
            channel.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
```
