### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Class java.lang.reflect.Field.getType()' on a null object reference

### ISSUE THREAD

**Issue by metalmatze** [pardom-zz/ActiveAndroid#313]
Hey, thanks for creating ActiveAndroid. I'm really happy so far.

But after creating a release build of my project the app is now crashing.
This happens on a Nexus5 with Android 5.0 aswell as on a Nexus 7 with Android 4.4.2.
Everything works fine running a debug build while developing.

Thanks!

```
java.lang.RuntimeException: Unable to create application com.activeandroid.app.Application: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.reflect.Field.getType()' on a null object reference
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
at android.app.ActivityThread.access$1500(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.reflect.Field.getType()' on a null object reference
at com.activeandroid.e.f.c(Unknown Source)
at com.activeandroid.e.f.c(Unknown Source)
at com.activeandroid.f.c(Unknown Source)
at com.activeandroid.f.onCreate(Unknown Source)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at com.activeandroid.b.b(Unknown Source)
at com.activeandroid.b.a(Unknown Source)
at com.activeandroid.a.a(Unknown Source)
at com.activeandroid.a.a(Unknown Source)
at com.activeandroid.a.a(Unknown Source)
at com.activeandroid.app.Application.onCreate(Unknown Source)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
... 9 more
```

**Comment by metalmatze** [comment]
So. I got an answer at StackOverflow: [https://stackoverflow.com/questions/27408902/attempt-to-invoke-virtual-method-java-lang-class-java-lang-reflect-field-gettyp/27409150](https://stackoverflow.com/questions/27408902/attempt-to-invoke-virtual-method-java-lang-class-java-lang-reflect-field-gettyp/27409150)

Seems like proguard obscures important stuff for reflection.

I found a progaurd configuration that worked for me. [https://github.com/rejasupotaro/Rebuild/blob/5246f6549fd854207c28d7b8179680034f81cbd9/Rebuild/proguard-release.txt#L68](https://github.com/rejasupotaro/Rebuild/blob/5246f6549fd854207c28d7b8179680034f81cbd9/Rebuild/proguard-release.txt#L68).

Maybe it should be added to the documentation?

**Comment by dotnick** [comment]
@MetalMatze I'm trying to setup Proguard with an app that uses AA and I'm facing the same issue. Using the proguard config from your link doesn't seem to work. Did you add anything else to the config?

**Comment by dotnick** [comment]
@MetalMatze Ignore my last comment, the solution you posted does work, when you include the config that comes with the SDK too. (getDefaultProguardFile('proguard-android.txt'))

I was adding the rules from your link to my 'proguard-rules.pro' file, and wasn't including the default one.

Thanks for the links.
