### ISSUE TITLE
Error inserting content into database - Multiline UTF-8 issue

### ISSUE THREAD

**Issue by jklimke** [pardom-zz/ActiveAndroid#315]
Hi,

in our application we deliver content that is fetch from a database using activeAndroid.
Since the application needs a mixture of user generated data and this content in one database, we insert the content using sql migrations scripts.

Now we got a problem with 

a) multiline strings as values if using the legacy sql parser

the SQL execution fails with the following exception

```
Caused by: android.database.sqlite.SQLiteException: unrecognized token: "'<p>Informationen für Neuberliner. Herzlich Willkommen in Berlin! Die Berlin Partner-App hilft beim Ankommen in der Hauptstadt. Was müssen Neu-Berliner bei ihrem Umzug nach Berlin beachten? Wo finde ich eine passende Wohnung? Wo muss ich mich anmelden, wie kann ich eine Aufenthaltserlaubnis beantragen, wo finde ich passende Kinderbetreuungsmöglichkeiten? Dieses Angebot gibt, auch mit Hilfe des offiziellen 3D-Stadtmodells, einen ersten Überblick.</p>
    <h4>Herausgeber</h4>
    Die App "New in Berlin" ist ein Angebot des Business Location Center Berlin.<br><br>
    <a href="http://www.businesslocationcenter.de"><img alt="" title="" src="media/W1siZiIsIjIwMTQvMDkvMTkvMDBfMjdfMzNfMjY4X2ZpbGUiXSxbInAiLCJ0aHVtYiIsIjEyNXg2MCJdXQ.png" class="" height="50"></a>&nbsp &nbsp&nbsp" (code 1): , while compiling: INSERT INTO "topic_translations" VALUES(19,10,'de','2014-07-29 10:11:46.536734','2014-09-23 00:17:13.892895','Über "New in Berlin"','<p>Informationen für Neuberliner. Herzlich Willkommen in Berlin! Die Berlin Partner-App hilft beim Ankommen in der Hauptstadt. Was müssen Neu-Berliner bei ihrem Umzug nach Berlin beachten? Wo finde ich eine passende Wohnung? Wo muss ich mich anmelden, wie kann ich eine Aufenthaltserlaubnis beantragen, wo finde ich passende Kinderbetreuungsmöglichkeiten? Dieses Angebot gibt, auch mit Hilfe des offiziellen 3D-Stadtmodells, einen ersten Überblick.</p>
    <h4>Herausgeber</h4>
    Die App "New in Berlin" ist ein Angebot des Business Location Center Berlin.<br><br>
    <a href="http://www.businesslocationcenter.de"><img alt="" title="" src="media/W1siZiIsIjIwMTQvMDkvMTkvMDBfMjdfMzNfMjY4X2ZpbGUiXSxbInAiLCJ0aHVtYiIsIjEyNXg2MCJdXQ.png" class="" height="50"></a>&nbsp &nbsp&nbsp
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:882)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:493)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1663)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1594)
            at com.activeandroid.DatabaseHelper.executeLegacySqlScript(DatabaseHelper.java:256)
            at com.activeandroid.DatabaseHelper.executeSqlScript(DatabaseHelper.java:221)
            at com.activeandroid.DatabaseHelper.executeMigrations(DatabaseHelper.java:187)
```

b) special multi byte characters when using the SQLParser class (SQL_PARSER_DELIMITED option)

the sql file is parsed and executing without any exceptions thrown, but the multibyte characters are not inserted correctly. This is probably because of the Tokenizer class is working char and append each char to a string, which does not work for mutli byte utf-8 characters like umlauts.

Is there any idea how to solve this ?

**Comment by kchygoe** [comment]
Hi, I've met same issue in my app.
I confirmed following conditions.
1. Using SQL_PARSER_DELIMITED would cause multibyte characters inserted uncorrectly
2. Using SQL_PARSER_LEGACY with multiline sql sentence will fail.

So the workaround here is,
- Use SQL_PARSER_LEGACY
- Write each SQL sentence in single line

For example, use SQL_PARSER_LEGACY with

```
CREATE TABLE test ( 
   'Id' INTEGER PRIMARY KEY NOT NULL,
   'val1' INTEGER,
   'val2' INTEGER
);
```

should be
`CREATE TABLE test ( 'Id' INTEGER PRIMARY KEY NOT NULL, 'val1' INTEGER, 'val2' INTEGER);`

I hope this will help you as well.
