### ISSUE TITLE
NoClassDefFoundError on start application

### ISSUE THREAD

**Issue by ppamorim** [pardom-zz/ActiveAndroid#322]
Hi , I'm facing this error when I try to build the project for Android Lollipop , Android 4.4 works perfectly , but above it gives this error. What could it be?
I'm using the latest build of ActiveAndroid.

Process: com.app.app.app, PID: 2296
    java.lang.NoClassDefFoundError: com.google.android.gms.internal.gf$a
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.content.ContentProvider.onCreate(ContentProvider.java:39)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1686)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1655)
            at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by matale** [comment]
Try the solution here http://stackoverflow.com/questions/23907037/how-to-disable-scanning-for-model-in-activeandroid/

**Comment by ppamorim** [comment]
Not working.

**Comment by Pierry** [comment]
Try this:
http://stackoverflow.com/a/26626940/1738135
