### ISSUE TITLE
Top-Level Exception 

### ISSUE THREAD

**Issue by ppamorim** [pardom-zz/ActiveAndroid#324]
Some strange error when I compile. If I clean the project, work perfectly.  

```
Error:Execution failed for task ':mobile:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /home/pedro/Android/Sdk/build-tools/21.1.1/dx --dex --incremental --no-strict --no-optimize --output /home/app/Documents/Projetos/app/mobile/build/intermediates/dex/debug --input-list=/home/app/Documents/Projetos/app/mobile/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
        2
  Output:
        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/activeandroid/ActiveAndroid;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
                at com.android.dx.command.dexer.Main.run(Main.java:245)
                at com.android.dx.command.dexer.Main.main(Main.java:214)
                at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by waflecl** [comment]
This happens because you have the same library more than once
