### ISSUE TITLE
java.lang.NoClassDefFoundError: com.amazon.device.associates, when including amazon-mobile-assocites apk

### ISSUE THREAD

**Issue by joshuarose** [pardom-zz/ActiveAndroid#329]
When running version 1.0.54 or 1.0.64 of amazon-mobile-associates sdk, the call to ActiveAndroid.initialize() will throw a NoClassDefFoundError with the following stack trace.

java.lang.NoClassDefFoundError: com.amazon.device.associates.as
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)

**Comment by joshuarose** [comment]
As a workaround adding the metadata for my specific model classes works.Following these instructions for the wiki. 

Speeding up application startup

ActiveAndroid will look through all your files to find your Model classes. This process can be very slow if you have a lot of dependencies. To speed up this process, specify your Model classes explicitely in your AndroidManifest:
