### ISSUE TITLE
Building Apps with Over 65K Methods causes NoClassDefFoundError

### ISSUE THREAD

**Issue by NeoLSN** [pardom-zz/ActiveAndroid#330]
Building Apps with Over 65K Methods will cause:

java.lang.NoClassDefFoundError: com.amazon.device.associates.as
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:308)
at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
at com.activeandroid.ModelInfo.(ModelInfo.java:63)
at com.activeandroid.Cache.initialize(Cache.java:66)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)

How to prevent this happen?

**Comment by mechinn** [comment]
https://developer.android.com/tools/building/multidex.html

**Comment by NeoLSN** [comment]
This exception happened after I do what you posted. If I didn't use multidex solution, I can't even build an apk file.

**Comment by ultraon** [comment]
Hi, you should declare all your models in the manifest, see Active Android manual.

**Comment by NeoLSN** [comment]
I read the ActiveAndroid wiki again but I didn't see how to declare all my models in the manifest. Can you give me a link which page you said?

**Comment by NeoLSN** [comment]
```
<meta-data
android:name="AA_MODELS"
android:value="com.myapp.model.Item, com.myapp.model.Category" />
```

Sorry, that my bad and thank you for your help.
