### ISSUE TITLE
One-to-many problem

### ISSUE THREAD

**Issue by dmitrikudrenko** [pardom-zz/ActiveAndroid#335]
I have two classes:

```
@Table(name = "job", id = BaseColumns._ID)
public class Job extends Model implements Serializable {
    public static final String CUBA_ID = "cuba_id";
    @Column(name = CUBA_ID, unique = true, onUniqueConflict = Column.ConflictAction.REPLACE)
    public String id;

    @Column(name = "number")
    public String number;

    @Column(name = "account")
    public String account;

    @Column(name = "service")
    public String service;

    @Column(name = "job_type")
    public JobType jobType;

    @Column(name = "job_date")
    public Date jobDate;

    @Column(name = "job_date_ex")
    public Date jobDateEx;

    @Column(name = "job_status")
    public JobStatus jobStatus;

    public List<Address> addresses;
}
```

```
@Table(name = "address")
public class Address extends Model {
    @Column(name = "address")
    public String address;

    @Column(name = "lat")
    public Double lat;

    @Column(name = "lon")
    public Double lon;

    @Column(name = "job")
    public Job job;
}
```

When I try to insert Job-object I get an exception:

```
android.database.sqlite.SQLiteException: foreign key mismatch (code 1): , while compiling: INSERT INTO job(job_date,cuba_id,job_type,_id,service,account,number,job_status,job_date_ex) VALUES (?,?,?,?,?,?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1118)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:691)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1589)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1461)
            at com.activeandroid.Model.save(Model.java:155)
            at com.haulmont.chase.loaders.JobsLoader.saveJobs(JobsLoader.java:38)
            at com.haulmont.chase.loaders.JobsLoader.backgroundLoading(JobsLoader.java:27)
            at com.haulmont.chase.loaders.JobsLoader.backgroundLoading(JobsLoader.java:18)
            at com.haulmont.chase.loaders.AbstractLoader.loadInBackground(AbstractLoader.java:33)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
```

I think the cause is in wrong one-to-many assotiation.

**Comment by dmitrikudrenko** [comment]
Object what I insert has only one filled field - id

**Comment by ultraon** [comment]
If you create your object than serialize it (for putting in Bundle for example), then deserialize and try to save it -> it will by error, because Model is not implemented Serializable interface

**Comment by dmitrikudrenko** [comment]
Well, it doesn't solve the problem.

```
02-05 16:22:52.159    1349-1370/com.haulmont.chase E/SQLiteLog﹕ (1) foreign key mismatch - "address" referencing "job"
02-05 16:22:52.174    1349-1370/com.haulmont.chase E/SQLiteDatabase﹕ Error inserting number=null job_date_ex=null job_type=null account=null service=null job_status=null _id=null job_date=null cuba_id=f702d064-8d8a-c5a7-231f-e156a7f22a82
    android.database.sqlite.SQLiteException: foreign key mismatch - "address" referencing "job" (code 1): , while compiling: INSERT INTO job(number,job_date_ex,job_type,account,service,job_status,_id,job_date,cuba_id) VALUES (?,?,?,?,?,?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.activeandroid.Model.save(Model.java:155)
            at com.haulmont.chase.loaders.JobsLoader.saveJobs(JobsLoader.java:38)
            at com.haulmont.chase.loaders.JobsLoader.backgroundLoading(JobsLoader.java:27)
            at com.haulmont.chase.loaders.JobsLoader.backgroundLoading(JobsLoader.java:18)
            at com.haulmont.chase.loaders.AbstractLoader.loadInBackground(AbstractLoader.java:33)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

```

**Comment by dmitrikudrenko** [comment]
I suggest that my db model is wrong.

**Comment by dmitrikudrenko** [comment]
I have imported database schema which was designed by ActiveAndroid.

```
CREATE TABLE address (Id INTEGER PRIMARY KEY AUTOINCREMENT, address TEXT, job INTEGER REFERENCES job(Id) ON DELETE NO ACTION ON UPDATE NO ACTION, lat REAL, lon REAL)
```

```
CREATE TABLE job (_id INTEGER PRIMARY KEY AUTOINCREMENT, account TEXT, cuba_id TEXT UNIQUE ON CONFLICT REPLACE, job_date INTEGER, job_date_ex INTEGER, job_status TEXT, job_type TEXT, number TEXT, service TEXT)
```

I see that "address" contains reference to "job", but not on _id column

**Comment by dmitrikudrenko** [comment]
Generally that is framework error, because reference should be on _id column from job

**Comment by dmitrikudrenko** [comment]
Ok, I've figured out. In Address class "id = BaseColumns._ID" should be in Table-annotation

**Comment by captain-miao** [comment]
@ray1984 remove custom _id,it's work. Thank you.
