### ISSUE TITLE
android.database.sqlite.SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by lujiajing1126** [pardom-zz/ActiveAndroid#340]
```
39  
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
40  
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
41  
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
42  
at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
43  
at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
44  
at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
45  
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
46  
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
47  
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
48  
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
49  
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
50  
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
51  
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
52  
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
53  
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:965)
54  
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:263)
55  
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
56  
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
57  
at com.activeandroid.Cache.openDatabase(Cache.java:106)
58  
at com.activeandroid.Cache.initialize(Cache.java:75)
59  
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
60  
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
61  
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
62  
at net.whosv.android.WhosvApplication.onCreate(WhosvApplication.java:106)
63  
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
64  
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4377)
65  
at android.app.ActivityThread.access$1500(ActivityThread.java:138)
66  
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
67  
at android.os.Handler.dispatchMessage(Handler.java:102)
68  
at android.os.Looper.loop(Looper.java:136)
69  
at android.app.ActivityThread.main(ActivityThread.java:5050)
70  
at java.lang.reflect.Method.invokeNative(Native Method)
71  
at java.lang.reflect.Method.invoke(Method.java:515)
72  
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
73  
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
74  
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by matteinn** [comment]
Hey @lujiajing1126 , did you ever find a workaround for this?
