### ISSUE TITLE
The need of support package V4.

### ISSUE THREAD

**Issue by amirfazwan** [pardom-zz/ActiveAndroid#366]
I encountered this error and solved by adding support package to gradle file.
I think this info should goes into the 'Getting Started' page.

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/LruCache;
            at com.activeandroid.Cache.initialize(Cache.java:73)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
            at com.activeandroid.app.Application.onCreate(Application.java:25)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by matbos** [comment]
Had similiar issue, resolved it by downloading sources and building the library jar myself.

**Comment by jayhar006** [comment]
what do you mean downloading sources? what will i download please help

**Comment by matbos** [comment]
I meant to download sources of ActiveAndroid and build the library by yourself.
