### ISSUE TITLE
 android.database.sqlite.SQLiteDiskIOException: disk I/O error ONLY At first run!

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [pardom-zz/ActiveAndroid#379]
App runs and creates database and tables correctly but when i try to save models, i get this exception.
But when app crashes and i relunch the app, the error doesn't happen anymore! and saves and loads models very well!

```
06-15 00:14:50.467  18409-18409/ E/SQLiteDatabase﹕ Error inserting from_number=+266696687 duration=5 session=f16a90e3-3ba7-4941-878b-22cb103a54b3 ownerId=ca0c96715b843fa0b35b57118a00191c to_number=16699990089 tab=all remoteId=b3db24018f977af5a1e63badc301ec2c Id=null date=2015-03-16 09:34:21 cost=0.15
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
        at com.activeandroid.Model.save(Model.java:155)
        at .model.HistoryRecordProvider$1.run(HistoryRecordProvider.java:65)
        at .model.HistoryRecordProvider.saveHistoryRecord(HistoryRecordProvider.java:73)
        at .model.HistoryRecordProvider.insert(HistoryRecordProvider.java:148)
        at .view.fragment.CallLogFragmentAll$2.success(CallLogFragmentAll.java:114)
        at .view.fragment.CallLogFragmentAll$2.success(CallLogFragmentAll.java:107)
        at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by manojnagar** [comment]
Any update on this?

**Comment by vivek50** [comment]
I am getting the same error...
any solution for this error??
