### ISSUE TITLE
Is it safe to use this tool for multi thread operating databases?

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [pardom-zz/ActiveAndroid#391]

**Comment by IvanMurzak** [comment]
I have a problem with this.
ActiveAndroid doesn't respond to Select request.
There is dead thread stacktrace:

``` java
"Thread-89472@5201" prio=5 waiting
  java.lang.Thread.State: WAITING
     blocks Thread-89472@5201
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.Thread.parkFor(Thread.java:1220)
      - locked <0x147b> (a java.lang.Object)
      at sun.misc.Unsafe.park(Unsafe.java:299)
      at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
      at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
      at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
      at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
      at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
      at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
      at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
      at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
      at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
      at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
      at com.activeandroid.util.SQLiteUtils.processCursor(SQLiteUtils.java:332)
      at com.activeandroid.util.SQLiteUtils.rawQuery(SQLiteUtils.java:107)
      at com.activeandroid.util.SQLiteUtils.rawQuerySingle(SQLiteUtils.java:122)
      at com.activeandroid.query.From.executeSingle(From.java:311)
```

It happens after creating few threads and combo with transactions.

**Comment by IvanMurzak** [comment]
No, it was my mistake. I reproduce deadlock in my code, that's why other ActiveAndroid thread stacks, because I make an transaction in another thread, and lock database.
