### ISSUE TITLE
 java.lang.NoClassDefFoundError: org.codehaus.jackson.jaxrs.JacksonJsonProvider

### ISSUE THREAD

**Issue by thingLi** [pardom-zz/ActiveAndroid#405]
4.4 the following try to run, but in the 5.1.1 version of the report submitted to the wrong. Activeandroid.initialize () at Application;

E/AndroidRuntime(1199): java.lang.NoClassDefFoundError: org.codehaus.jackson.jaxrs.JacksonJsonProvider
E/AndroidRuntime(1199):     at java.lang.Class.classForName(Native Method)
 E/AndroidRuntime(1199):    at java.lang.Class.forName(Class.java:309)
 E/AndroidRuntime(1199):    at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:188)
 E/AndroidRuntime(1199):    at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
E/AndroidRuntime(1199):     at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
 E/AndroidRuntime(1199):    at com.activeandroid.Cache.initialize(Cache.java:66)
 E/AndroidRuntime(1199):    at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)

**Comment by thingLi** [comment]
The problem has been solved
Added in AndroidMainfest.xml
<meta-data
Android:name= "AA_MODELS" android:value= "entity class 1, entity class 2,..."
