### ISSUE TITLE
java.lang.NoClassDefFoundError: org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by tacoman667** [pardom-zz/ActiveAndroid#422]
I am getting this issue on the line in my Application Class that runs `ActiveAndroid.initialize(this)`. This crashes the application immediately after startup.

I am using groovy 2.4.5 to run my applications and this only popped up after the 5.1.0 Android OS update. I am also using ActiveAndroid 3.0 release.

```
java.lang.NoClassDefFoundError: org.codehaus.groovy.vmplugin.v7.Java7
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:309)
     at com.activeandroid.ReflectionUtils.getParsers(ReflectionUtils.java:158)
     at com.activeandroid.Registry.initialize(Registry.java:100)
     at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:8)
```

**Comment by prashantwosti** [comment]
Probably its related to android [65K reference limit.](https://developer.android.com/tools/building/multidex.html) 

All you have to do is: 
1. Add multidex dependency `compile 'com.android.support:multidex:1.0.1'` 
2. Declare all of your [model classes explicitly in the manifest](https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model#speeding-up-application-startup). and
3. In your application class, 

``` java
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

@Override
    public void onCreate() {
        super.onCreate();
        ActiveAndroid.initialize(context);
```

I hope this solved your issue.

**Comment by fattchris** [comment]
I have the same issue. Unfortunately, multidex is already in place and the issue persists. Like the commenter above, this is only an issue on Android 5.1+

**Comment by tacoman667** [comment]
@prashantwosti Thanks for the suggestion but we are using groovy and so multidex is already up and running for a while now. Any other ideas?

**Comment by Mistic92** [comment]
We have same problem.

ActiveAndroid.initialize(getApplicationContext(), true);

```
11-18 18:42:03.200 22151-22151/com.positivegeeks.daywithscrum I/art: Rejecting re-init on previously-failed class java.lang.Class<groovyjarjarantlr.debug.misc.ASTFrame$1>
11-18 18:42:03.201 22151-22151/com.positivegeeks.daywithscrum I/art: Rejecting re-init on previously-failed class java.lang.Class<groovyjarjarantlr.debug.misc.ASTFrame$1>
11-18 18:42:03.217 22151-22151/com.positivegeeks.daywithscrum E/ActiveAndroid: Couldn't create class.
                                                                               java.lang.ClassNotFoundException: groovyjarjarantlr.debug.misc.ASTFrame$1
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.Class.forName(Class.java:324)
                                                                                   at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
                                                                                   at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
                                                                                   at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
                                                                                   at com.activeandroid.Cache.initialize(Cache.java:66)
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:38)
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass$1.run(ApplicationClass.java:41)
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass.onCreate(ApplicationClass.java:47)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                   at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "groovyjarjarantlr.debug.misc.ASTFrame$1" on path: DexPathList[[zip file "/data/app/com.positivegeeks.daywithscrum-2/base.apk"],nativeLibraryDirectories=[/data/app/com.positivegeeks.daywithscrum-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at java.lang.Class.classForName(Native Method) 
                                                                                   at java.lang.Class.forName(Class.java:324) 
                                                                                   at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187) 
                                                                                   at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152) 
                                                                                   at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63) 
                                                                                   at com.activeandroid.Cache.initialize(Cache.java:66) 
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44) 
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:38) 
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass$1.run(ApplicationClass.java:41) 
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass.onCreate(ApplicationClass.java:47) 
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
                                                                                   at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                Suppressed: java.lang.NoClassDefFoundError: groovyjarjarantlr.debug.misc.ASTFrame$1
                                                                                   at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                                   at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                                   at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                                   at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                                        ... 22 more
                                                                                Suppressed: java.lang.ClassNotFoundException: groovyjarjarantlr.debug.misc.ASTFrame$1
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                        ... 21 more
                                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-18 18:42:03.217 22151-22151/com.positivegeeks.daywithscrum I/art: Rejecting re-init on previously-failed class java.lang.Class<groovyjarjarantlr.debug.misc.ASTFrame$MyTreeSelectionListener>
11-18 18:42:03.217 22151-22151/com.positivegeeks.daywithscrum I/art: Rejecting re-init on previously-failed class java.lang.Class<groovyjarjarantlr.debug.misc.ASTFrame$MyTreeSelectionListener>
11-18 18:42:03.218 22151-22151/com.positivegeeks.daywithscrum E/ActiveAndroid: Couldn't create class.
                                                                               java.lang.ClassNotFoundException: groovyjarjarantlr.debug.misc.ASTFrame$MyTreeSelectionListener
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.Class.forName(Class.java:324)
                                                                                   at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
                                                                                   at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
                                                                                   at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
                                                                                   at com.activeandroid.Cache.initialize(Cache.java:66)
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:38)
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass$1.run(ApplicationClass.java:41)
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass.onCreate(ApplicationClass.java:47)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                   at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "groovyjarjarantlr.debug.misc.ASTFrame$MyTreeSelectionListener" on path: DexPathList[[zip file "/data/app/com.positivegeeks.daywithscrum-2/base.apk"],nativeLibraryDirectories=[/data/app/com.positivegeeks.daywithscrum-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at java.lang.Class.classForName(Native Method) 
                                                                                   at java.lang.Class.forName(Class.java:324) 
                                                                                   at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187) 
                                                                                   at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152) 
                                                                                   at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63) 
                                                                                   at com.activeandroid.Cache.initialize(Cache.java:66) 
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44) 
                                                                                   at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:38) 
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass$1.run(ApplicationClass.java:41) 
                                                                                   at com.positivegeeks.daywithscrum.ApplicationClass.onCreate(ApplicationClass.java:47) 

AND MANY MORE
```
