### ISSUE TITLE
NullPointerException when minifyEnabled=true

### ISSUE THREAD

**Issue by nscherer** [pardom-zz/ActiveAndroid#423]
When running a release build with minifyEnabled=true, I get this exception:

``` java
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime: java.lang.RuntimeException: Unable to create application com.activeandroid.app.Application: java.lang.NullPointerException
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4618)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.access$1600(ActivityThread.java:169)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5487)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:  Caused by: java.lang.NullPointerException
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.util.SQLiteUtils.c(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.util.SQLiteUtils.c(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.f.c(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.f.onCreate(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.b.b(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.b.a(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.a.a(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.a.a(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.a.a(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.activeandroid.app.Application.onCreate(Unknown Source)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4615)
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.access$1600(ActivityThread.java:169) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5487) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
10-15 14:02:01.814 2574-2574/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

If I set minifyEnabled to false, no error.  I would provide relevant code snippets but as you can see the stack trace does not reference any of my code, it's all AA and Android OS.

**Comment by Pozzoooo** [comment]
I'm not sure by the stack trace, but it works fine to me with this parameter on "proguard-rules.txt":

-keep class "$yourpackage".model.*\* { _; } (Change "$yourpackage" by your packge :))
-keep class com.activeandroid._\* { _; }
-keepattributes *Annotation_,Signature

**Comment by nscherer** [comment]
Thanks for the suggestion, but it didn't work for me.  I tried that with and without "public", I tried 

-keep public class \* extends com.activeandroid.Model

I tried -keeping each model class explicitly, always the same crash.  What does the {;} mean?

**Comment by Pozzoooo** [comment]
Github is removing *, sorry see it only now, pasting again escaping:

-keep class com.activeandroid.** { *; }
-keep class package.model.** { *; }
-keepattributes *Annotation*,Signature

The { *; } is supposed to keep all methods/members untouched as well.

**Comment by nscherer** [comment]
That did it!  Thank you!

**Comment by Pozzoooo** [comment]
Great! You may close this issue then.
