### ISSUE TITLE
NoClassDefFoundError，FingerprintManagerCompatApi23

### ISSUE THREAD

**Issue by feng88724** [pardom-zz/ActiveAndroid#431]
java.lang.NoClassDefFoundError: android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23

ROM,Android 5.0.1

**Comment by feng88724** [comment]
```
11-25 19:37:06.248: E/AndroidRuntime(17521): FATAL EXCEPTION: main
11-25 19:37:06.248: E/AndroidRuntime(17521): Process: cn.xxx.and, PID: 17521
11-25 19:37:06.248: E/AndroidRuntime(17521): java.lang.NoClassDefFoundError: android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
11-25 19:37:06.248: E/AndroidRuntime(17521):    at java.lang.Class.classForName(Native Method)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at java.lang.Class.forName(Class.java:308)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.activeandroid.ReflectionUtils.getModelClasses(ReflectionUtils.java:83)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.activeandroid.DatabaseHelper.onCreate(DatabaseHelper.java:46)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.activeandroid.Registry.openDatabase(Registry.java:149)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.activeandroid.Registry.initialize(Registry.java:107)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:8)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at cn.xxx.and.MyApplication.onCreate(MyApplication.java:22)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.app.ActivityThread.access$1900(ActivityThread.java:152)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.os.Looper.loop(Looper.java:135)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at android.app.ActivityThread.main(ActivityThread.java:5538)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at java.lang.reflect.Method.invoke(Native Method)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at java.lang.reflect.Method.invoke(Method.java:372)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
11-25 19:37:06.248: E/AndroidRuntime(17521):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
```

**Comment by jlhonora** [comment]
Try adding the AA_MODELS tag in your manifest, more info here: https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model#speeding-up-application-startup

**Comment by feng88724** [comment]
Thandks, AA_MODELS is used to speed up.

I change  activeandroid-3.0.jar  to  activeandroid-3.1-beta.jar,  problem fixed.

**Comment by 7xrobin** [comment]
I'm having the same problem and tried the both solutions but didn't work.

 My gradle:

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

```
defaultConfig {
    applicationId "com.example.vntcaro.myapp"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    wearApp project(':wear')
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:8.1.0'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile project(':shared')
    compile files('libs/activeandroid-3.0.jar')
    compile 'com.android.support:multidex:1.0.0'
}

**Comment by PtiPingouin** [comment]
Any update on this?

**Comment by dounaka** [comment]
+1

**Comment by gooner22** [comment]
adding the AA_MODELS tag worked for me.
thank you - @jlhonora !

**Comment by sainihimanshu** [comment]
Updating to 3.1 beta jar worked for me.

**Comment by OguzErdi** [comment]
+1

**Comment by AnthonyKoueik** [comment]
```
    It's not fixed for me . anyone not using jar ?


    minSdkVersion 16
    targetSdkVersion 24
    versionCode 1
    versionName "1.0"

compile 'com.android.support:appcompat-v7:24.2.1'
compile 'com.android.support:design:24.2.1'
compile 'com.android.support:cardview-v7:24.2.1'
compile 'com.android.support:multidex:1.0.0'

compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
```

**Comment by 7xrobin** [comment]
Update the ActiveAndroid works for me.

**Comment by AnthonyKoueik** [comment]
Hello what ActiveAndroid  version you are using ?
compile 'com.michaelpardo:activeandroid:??????????????'
thank you

**Comment by 7xrobin** [comment]
compile files('libs/activeandroid-3.0.jar')
