### ISSUE TITLE
Encryption Support?

### ISSUE THREAD

**Issue by nathan-yuen** [pardom-zz/ActiveAndroid#45]
Is there any chance to bring in encryption?
or can I simply use sqlcipher?
https://github.com/sqlcipher/android-database-sqlcipher

**Comment by pardom-zz** [comment]
I don't have plans to build in encryption. I have projects that require encryption, and I just save strings encrypted with Cipher: https://developer.android.com/reference/javax/crypto/Cipher.html

**Comment by nathan-yuen** [comment]
Thanks for replying
but i have managed to use SQLCipher with ActiveAndroid :+1:

**Comment by stormzhang** [comment]
I want to use ActiveAndroid, and I also need to encrypt my data. Any solutions to work with sqlcipher?

**Comment by ticolucci** [comment]
Hey @nathan-yuen ,
Can you elaborate a little how you did the integration between SQLCipher and ActiveAndroid?

I'm currently studying the possibility of using AA in a new project, but encryption is a requirement and the previous project uses SQLCipher. So it would be a winwin situation to use both =)

**Comment by zsiegel** [comment]
For @ticolucci and others wanting an example you can check out my forked version of ActiveAndroid with SQLCipher [here](https://github.com/zsiegel/ActiveAndroid-Secure)

**Comment by ticolucci** [comment]
Thanks @zsiegel !

**Comment by zsiegel** [comment]
Just as a word of caution I threw this together in a few hours. There may be issues with it. I will try and solidify it into a pull request later.

On November 14, 2013 at 12:45:25 PM, Thiago R. Colucci (notifications@github.com) wrote:

Thanks @zsiegel !

**Comment by sincerekamal** [comment]
@zsiegel but what should i do to remove encryption from the database, for example, for debugging purpose, I may need to export it to my PC to look into the sqlite database.. how can i do that ?

And also how can I change the password from version to version ? how it would react ?
For instance, in the version 0.1 the password is "abc" and the data is now encrypted with it
And in the version 0.2 i would like to change the password to "xyz, because i think the password "abc" is now known to many. So after the changing the password, can it decrypt the data encrypted with "abc" ?

**Comment by zsiegel** [comment]
@sincerekamal changing the password needs to be done at the raw sql level.

For example you can use something like to change the password...

``` java
SQLiteDatabase database = SQLiteDatabase.openDatabase(getDatabasePath("db").getPath() , oldPass, null,0) ;
database.rawExecSQL("PRAGMA rekey = '"+newPass+"';");
database.close();
```

In terms of removing the password all together for inspection elsewhere that is not something I have ever done but I imagine there is a set of sql commands that can be found in the SqlCipher docs to help with that.

**Comment by SureshSc** [comment]
@zsiegel i am getting below error if i try to integrate in my project 
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.gyanmatrix.loany, PID: 4380
                                                                    java.lang.NoClassDefFoundError: com.activeandroid.DatabaseHelper
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.Class.forName(Class.java:309)
                                                                        at com.activeandroid.ModelInfo.scanForModelClasses(Unknown Source)
                                                                        at com.activeandroid.ModelInfo.scanForModel(Unknown Source)
                                                                        at com.activeandroid.ModelInfo.<init>(Unknown Source)
                                                                        at com.activeandroid.Cache.initialize(Unknown Source)
                                                                        at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
                                                                        at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
                                                                        at com.activeandroid.ActiveAndroid.initialize(Unknown Source)
                                                                        at com.activeandroid.app.Application.onCreate(Unknown Source)
                                                                        at com.gyanmatrix.loany.LoanyApp.onCreate(LoanyApp.java:304)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java`
