### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by bpappin** [pardom-zz/ActiveAndroid#456]
`cx2s-bpappin:ActiveAndroid bpappin$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
cx2s-bpappin:ActiveAndroid bpappin$ brew update maven
cx2s-bpappin:ActiveAndroid bpappin$ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ActiveAndroid - Parent
[INFO] ActiveAndroid
[INFO] ActiveAndroid - Tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ActiveAndroid - Parent 3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ activeandroid-parent ---
[INFO] Installing /Users/bpappin/Workspace/ActiveAndroid/pom.xml to /Users/bpappin/.m2/repository/com/activeandroid/activeandroid-parent/3.1-SNAPSHOT/activeandroid-parent-3.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ActiveAndroid 3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
    at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    ... 5 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ActiveAndroid - Parent ............................. SUCCESS [  0.074 s]
[INFO] ActiveAndroid ...................................... FAILURE [  0.189 s]
[INFO] ActiveAndroid - Tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.821 s
[INFO] Finished at: 2016-03-12T09:13:45-05:00
[INFO] Final Memory: 16M/309M
[INFO] --------------------------------------------------------------`

**Comment by bpappin** [comment]
Just ran into this again with the latest code.
