### ISSUE TITLE
Error on Android Studio 2.0

### ISSUE THREAD

**Issue by dev4lifes** [pardom-zz/ActiveAndroid#467]
I run very good on Android studio 1.5 but today I update to 2.0 and this lib made error NullPointerException getTableName. Can you help me? Thanks

```
Process: net.dev4life.stxd, PID: 12237
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
                                                                       at com.activeandroid.Cache.getTableName(Cache.java:156)
                                                                       at com.activeandroid.query.From.addFrom(From.java:169)
                                                                       at com.activeandroid.query.From.toSql(From.java:250)
                                                                       at com.activeandroid.query.From.executeSingle(From.java:311)
                                                                       at net.dev4life.stxd.support.sqlite.LookUpTable.findFactorSlab(LookUpTable.java:33)
                                                                       at net.dev4life.stxd.fragment.structural.SlabTwoWayFragment.handleChooseTypeSlab(SlabTwoWayFragment.java:296)
                                                                       at net.dev4life.stxd.fragment.structural.SlabTwoWayFragment.calculate(SlabTwoWayFragment.java:146)
                                                                       at net.dev4life.stxd.fragment.structural.SlabTwoWayFragment$$ViewBinder$2.doClick(SlabTwoWayFragment$$ViewBinder.java:75)
                                                                       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                       at com.gc.materialdesign.views.Button.makeCircle(Button.java:135)
                                                                       at com.gc.materialdesign.views.ButtonRectangle.onDraw(ButtonRectangle.java:145)
                                                                       at android.view.View.draw(View.java:16180)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15103)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15063)
                                                                       at android.view.View.getDisplayList(View.java:15126)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                    at android.view.View.update
```

**Comment by EdwinCL** [comment]
Same here.

I have to turn off Instant Run to have my app working...

**Comment by julioabdilla** [comment]
i've turned off instant run and still not working..

**Comment by BenoitDuffez** [comment]
It's not linked to Android Studio 2.0 but rather `com.android.tools.build:gradle:2.0.0`.

Using `com.android.tools.build:gradle:1.5.0` makes it work again, but we can't use Instant Run then.

**Comment by yjchieng** [comment]
Same here. Even when running on actual device.

**Comment by tsimmi** [comment]
Same here.
Thanks @BenoitDuffez 
Using `com.android.tools.build:gradle:1.5.0`, does the trick.
Unfortunately this can only be a temporary solution for the problem.

**Comment by Axolot1** [comment]
you don't have to turn off the instant run. simply set 
<meta-data   android:name="AA_MODELS" android:value="your model path" />
inside application node  in AndroidManifest.xml, uninstall the your app before you run.

**Comment by victorg1991** [comment]
Thanks @Axolot1 Works like a charm!! 😍

**Comment by Axolot1** [comment]
@victorg1991 glad i it help :smile:

**Comment by yjchieng** [comment]
It works but now the app needs 5+sec to start up...

**Comment by Gregliest** [comment]
Does anyone know what is breaking here?

**Comment by jlhonora** [comment]
I made a small working sample for Android Studio 2.0: https://github.com/jlhonora/activeandroid-example . `AA_MODELS` definition makes the difference between crashing or not.

**Comment by victorg1991** [comment]
Changing AndroidManifest.xml not working properly, finally I added this (which is basically the same that change the Android manifest, but this works well):
Initialize active android like this
`Configuration.Builder config = new Configuration.Builder(this);
config.addModelClasses(Model1.class, Model2.class);
ActiveAndroid.initialize(config.create());`

**Comment by BenoitDuffez** [comment]
I'm not getting this anymore with Android Studio 2.1 (and AA 3.1.0-SNAPSHOT).

Tried `com.android.tools.build:gradle:1.5.0`,  `com.android.tools.build:gradle:2.0.0`, and `com.android.tools.build:gradle:2.1.0`; none of them cause the crash anymore.

Anyone confirms?

**Comment by hikumar1** [comment]
Its not working with latest gradle versions, Can anyone let me know what changes to be done to make it working on higher versions. it doesn't work for me with  com.android.tools.build:gradle:2.1.0.

**Comment by victorg1991** [comment]
@hikumar1 did you tried the proposed solutions?

**Comment by beingsagir** [comment]
It is still confusing ! 
- Turned off the Instant Run
- I have updated the manifest file, After adding all those models I am using, only one model is operational.
- I have tried the Victorg's way too. I can not recognize "addModelClasses" under config. And it is not the proper way to initialize all those models in main class I guess. We need to look for one ultimate & globally acceptable solution. 

Here Is one thread in StackOverflow : [Go To](http://stackoverflow.com/questions/36490573/why-active-android-is-not-working-with-gradle-2-0)

**Comment by victorg1991** [comment]
Did you add the correct import?
import com.activeandroid.Configuration

This is working for me

**Comment by beingsagir** [comment]
@victorg1991 
I am initializing it in main activity constructor and it is not working. Do I need to initialize all the models sheparating by comma in other place(s).

**Comment by victorg1991** [comment]
I think that is all you have to do. 🤔
Did you wipe de app data and unistall before test it?
