### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference

### ISSUE THREAD

**Issue by stoefln** [pardom-zz/ActiveAndroid#474]
Since I upgraded AndroidStudio and the gradle plugin I am getting a strange error in my app:
previous version: com.android.tools.build:gradle:1.3.0
current version: com.android.tools.build:gradle:2.0.0

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
at com.activeandroid.Cache.getTableName(Cache.java:156)
at com.activeandroid.query.From.addFrom(From.java:169)
at com.activeandroid.query.From.toSql(From.java:250)
at com.activeandroid.query.From.execute(From.java:298)
at at.seesmart.app.model.Product.getAll(Product.java:50)
at at.seesmart.app.activity.LoadProductActivity.loadProducts(LoadProductActivity.java:75)
at at.seesmart.app.activity.LoadProductActivity.onCreate(LoadProductActivity.java:70)
at android.app.Activity.performCreate(Activity.java:6251)
```

Any ideas?

**Comment by stoefln** [comment]
It really seems gradle related. Going back to gradle 1.3.0 it works again.

**Comment by victorg1991** [comment]
It's an instant run mode related issue. You can see some workarounds here 
https://github.com/pardom/ActiveAndroid/issues/467
Hope it helps

**Comment by XHiStone** [comment]
If instant run enable remove.This takes  4 seconds.
