### ISSUE TITLE
java.lang.SecurityException: Failed to find provider null for user 0; expected to find a valid ContentProvider for this authority

### ISSUE THREAD

**Issue by ieewbbwe** [pardom-zz/ActiveAndroid#553]
java.lang.SecurityException: Failed to find provider null for user 0; expected to find a valid ContentProvider for this authority

java.lang.SecurityException: Failed to find provider null for user 0; expected to find a valid ContentProvider for this authority
                                                       at android.os.Parcel.readException(Parcel.java:1942)
                                                       at android.os.Parcel.readException(Parcel.java:1888)
                                                       at android.content.IContentService$Stub$Proxy.notifyChange(IContentService.java:801)
                                                       at android.content.ContentResolver.notifyChange(ContentResolver.java:2046)
                                                       at android.content.ContentResolver.notifyChange(ContentResolver.java:1997)
                                                       at android.content.ContentResolver.notifyChange(ContentResolver.java:1967)
                                                       at com.activeandroid.Model.save(Model.java:162)

**Comment by rex3du** [comment]
any solutions for this one?

**Comment by d-rahul** [comment]
Did you find the solution? @ieewbbwe
