### ISSUE TITLE
[Crash] CursorWindowAllocationException - com.activeandroid.util.SQLiteUtils.processIntCursor

### ISSUE THREAD

**Issue by raghav2945** [pardom-zz/ActiveAndroid#575]
This is the most frequently reported crash on Firebase. This means that on average, this crash event for this issue occurred 6 times per user. And looking through the stack, it appears to be something related to cursor open/close. To determine the true cause, a thorough investigation is required. For the time being, I'm just going to share the information we have with us and request you to continue. 

**SDK version** : activeandroid:3.2.4

```
Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.audiomack/databases/Audiomack.db' of size 2097152 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:139)
       at android.database.CursorWindow.<init>(CursorWindow.java:120)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
       at com.activeandroid.util.SQLiteUtils.processIntCursor(SQLiteUtils.java:387)
       at com.activeandroid.util.SQLiteUtils.intQuery(SQLiteUtils.java:133)
       at com.activeandroid.query.From.count(From.java:333)
       at com.audiomack.data.database.MusicDAOImpl.premiumLimitedUnfrozenDownloadCount(MusicDAOImpl.kt:215)
       at com.audiomack.data.premiumdownload.PremiumDownloadRepository.getPremiumLimitedUnfrozenDownloadCount(PremiumDownloadRepository.kt:66)
       at com.audiomack.fragments.offline.DataDownloadsViewModel.getPremiumParams(DataDownloadsViewModel.kt:156)
       at com.audiomack.fragments.offline.DataDownloadsFragment.configureDownloadHeaderView(DataDownloadsFragment.kt:433)
       at com.audiomack.fragments.offline.DataDownloadsFragment.recyclerViewHeader(DataDownloadsFragment.kt:425)
       at com.audiomack.fragments.DataFragment.onViewCreated(DataFragment.java:154)
       at com.audiomack.fragments.offline.DataDownloadsFragment.onViewCreated(DataDownloadsFragment.kt:118)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
       at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540)
       at com.audiomack.ui.mylibrary.MyLibraryFragment$onViewCreated$$inlined$doOnLayout$1.onLayoutChange(View.kt:414)
       at android.view.View.layout(View.java:22109)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:783)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3258)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2754)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1840)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7937)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
       at android.view.Choreographer.doCallbacks(Choreographer.java:804)
       at android.view.Choreographer.doFrame(Choreographer.java:739)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by naXa777** [comment]
1. why do you want to use a library that was not updated for the last 7 years?
2. try forks, maybe the problem that you reported was already fixed by someone:
   * https://github.com/ImangazalievM/ReActiveAndroid - last updated in 2018
   * https://github.com/RileyGB/ProactiveAndroid - last updated in 2016
