### ISSUE TITLE
NullPointerException at com.activeandroid.Registry.getTableName(Registry.java:218)

### ISSUE THREAD

**Issue by benhirashima** [pardom-zz/ActiveAndroid#66]
ActiveAndroid looks great, but my first attempt at using it is giving me a NullPointerException. i'm using ActiveAndroid 3.0. android project target api level 17. eclipse ADT v22. my model:

```
@Table(name = "conditions")
public class Condition extends Model {
    @Column(name = "name")
    public String name;

    @Column(name = "date")
    public Date date;
}
```

instantiating this model with

```
Condition cond = new Condition();
```

stack trace excerpt:

```
05-23 13:50:15.751: E/AndroidRuntime(20355): Caused by: java.lang.NullPointerException
05-23 13:50:15.751: E/AndroidRuntime(20355):    at com.activeandroid.Registry.getTableName(Registry.java:218)
05-23 13:50:15.751: E/AndroidRuntime(20355):    at com.activeandroid.ReflectionUtils.getTableName(ReflectionUtils.java:26)
05-23 13:50:15.751: E/AndroidRuntime(20355):    at com.activeandroid.Model.<init>(Model.java:33)
05-23 13:50:15.751: E/AndroidRuntime(20355):    at com.benhirashima.Condition.<init>(Condition.java:60)
```

seems like a problem with getTableName, but i defined my table name as per the documentation. please advise.

**Comment by AaronRietschlin** [comment]
I was having this exact issue until I realized I didn't put the Application name in the manifest. 

```
<application 
...
  android:name=".YourApplicationNameHere"
...>
```

**Comment by benhirashima** [comment]
that was it. thanks nemisis!

**Comment by abhinavtripathi1993** [comment]
thanks dude,this was really helpful

**Comment by himanshu1706** [comment]
thanks nemisis, this resolved my problem.
