### ISSUE TITLE
Cannot instantiate POJO models via frameworks like Gson

### ISSUE THREAD

**Issue by mhamann** [pardom-zz/ActiveAndroid#75]
When attempting to use Gson to populate objects based on ActiveAndroid Models, the construction of the new object fails during the <init> phase. Gson attempts to do this via reflection.

This process works with the latest JAR (activeandroid-3.1-beta.jar) from https://github.com/pardom/ActiveAndroid/downloads, but does not work with JARs compiled from the latest source tree.

Here's the logcat based on my application (I'm loading a JSON resource through a 3rd party library, then using Gson to instantiate the objects, finally saving them to the DB with AA).

`06-09 18:42:28.908: W/System.err(8242): java.lang.RuntimeException: Failed to invoke public com.mhamann.versecards.domain.Course() with no args
06-09 18:42:28.916: W/System.err(8242):     at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
06-09 18:42:28.916: W/System.err(8242):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
06-09 18:42:28.916: W/System.err(8242):     at com.google.gson.Gson.fromJson(Gson.java:803)
06-09 18:42:28.916: W/System.err(8242):     at com.koushikdutta.ion.gson.GsonSerializer$1.transform(GsonSerializer.java:39)
06-09 18:42:28.916: W/System.err(8242):     at com.koushikdutta.ion.gson.GsonSerializer$1.transform(GsonSerializer.java:35)
06-09 18:42:28.916: W/System.err(8242):     at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
06-09 18:42:28.916: W/System.err(8242):     at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:81)
06-09 18:42:28.923: W/System.err(8242):     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:110)
06-09 18:42:28.923: W/System.err(8242):     at com.koushikdutta.async.parser.ByteBufferListParser$3.onCompleted(ByteBufferListParser.java:42)
06-09 18:42:28.923: W/System.err(8242):     at com.koushikdutta.async.DataEmitterBase.report(DataEmitterBase.java:16)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.FilteredDataEmitter$1.onCompleted(FilteredDataEmitter.java:24)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.DataEmitterBase.report(DataEmitterBase.java:16)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.http.AsyncHttpResponseImpl.report(AsyncHttpResponseImpl.java:107)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.http.AsyncHttpClient$2$2.report(AsyncHttpClient.java:263)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.FilteredDataEmitter$1.onCompleted(FilteredDataEmitter.java:24)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.DataEmitterBase.report(DataEmitterBase.java:16)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.FilteredDataEmitter$1.onCompleted(FilteredDataEmitter.java:24)
06-09 18:42:28.931: W/System.err(8242):     at com.koushikdutta.async.DataEmitterBase.report(DataEmitterBase.java:16)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.http.filter.ChunkedInputFilter.onDataAvailable(ChunkedInputFilter.java:99)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.Util.emitAllData(Util.java:20)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncSSLSocketWrapper$1.onDataAvailable(AsyncSSLSocketWrapper.java:96)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:33)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:62)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.Util.emitAllData(Util.java:20)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:162)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:647)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:31)
06-09 18:42:28.939: W/System.err(8242):     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:595)
06-09 18:42:28.947: W/System.err(8242): Caused by: java.lang.NullPointerException: key == null || value == null
06-09 18:42:28.947: W/System.err(8242):     at android.support.v4.util.LruCache.put(LruCache.java:117)
06-09 18:42:28.955: W/System.err(8242):     at com.activeandroid.Cache.addEntity(Cache.java:124)
06-09 18:42:28.955: W/System.err(8242):     at com.activeandroid.Model.<init>(Model.java:51)
06-09 18:42:28.955: W/System.err(8242):     at com.mhamann.versecards.domain.Course.<init>(Course.java:29)
06-09 18:42:28.955: W/System.err(8242):     at java.lang.reflect.Constructor.constructNative(Native Method)
06-09 18:42:28.955: W/System.err(8242):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-09 18:42:28.955: W/System.err(8242):     at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104)
06-09 18:42:28.962: W/System.err(8242):     ... 28 more`

**Comment by smarek** [comment]
Looks like an issue of LruCache, take a look at implementation in latest patch: https://github.com/vonloxley/activeandroid/commit/6d78a8219be7789c3bcfd985cea39997c159ab7c

**Comment by pardom-zz** [comment]
Gson requires that your Model have a constructor that takes no arguments. If you do not have one, but instead have one with arguments, you must add a constructor without any.

**Comment by mhamann** [comment]
Correct. My model did have a constructor with no arguments that called
super() on its parent. Same issue.

**Comment by dmitrikudrenko** [comment]
Is there solution?

**Comment by ultraon** [comment]
I had some problems with serialization children on Model with GSON, but i found out this decision (serialize and deserialize work good) and i used ActiveAndroid (sebbia fork):

``` java
new GsonBuilder()
                .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC)
                .serializeNulls()
                .create();
```

**Comment by dmitrikudrenko** [comment]
It didn't help me. I have several classes:

```
@Table(name = "job", id = BaseColumns._ID)
public class Job extends Model implements Serializable {
    public static final String CUBA_ID = "cuba_id";
    @Column(name = CUBA_ID, unique = true, onUniqueConflict = Column.ConflictAction.REPLACE)
    public String id;

    @Column(name = "number")
    public String number;

    @Column(name = "account")
    public String account;

    @Column(name = "service")
    public String service;

    @Column(name = "job_type")
    public JobType jobType;

    @Column(name = "job_date")
    public Date jobDate;

    @Column(name = "job_date_ex")
    public Date jobDateEx;

    @Column(name = "job_status")
    public JobStatus jobStatus;

    public List<Address> addresses;
}
```

```
@Table(name = "address")
public class Address extends Model {
    @Column(name = "address")
    public String address;

    @Column(name = "lat")
    public Double lat;

    @Column(name = "lon")
    public Double lon;

    @Column(name = "job")
    public Job job;
}
```

And that is my json:

```
{
    "resultCode": 0,
    "jobData": {
        "id": "f702d064-8d8a-c5a7-231f-e156a7f22a82",
        "number": "3",
        "account": "account1",
        "asset": "asset1",
        "service": "павып",
        "jobType": 10,
        "jobDate": "2015-02-05 12:25:48",
        "jobDateEx": null,
        "status": 110,
        "addresses": [
            {
                "address": "ulitsa Gastello, 43А, Samara, Samarskaya oblast', Russia, 443090",
                "lat": 53.224542,
                "lon": 50.194789
            }
        ]
    }
}
```

But I get exception 
`java.lang.RuntimeException: Failed to invoke public com.haulmont.chase.model.Address() with no args`

**Comment by ultraon** [comment]
Try to put explicit default constructor (without args) for each model, remove Serializable interface from Job class. I use this method in this way:

``` java
Gson gson = new GsonBuilder()
                .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC)
                .serializeNulls()
                .create();
String json = gson.toJson(myModel);
MyModel myDeserializedModel = gson.fromJson(json, MyModel.class)
```

**Comment by dmitrikudrenko** [comment]
I did what you've advised, but exception still thrown

**Comment by dmitrikudrenko** [comment]
OMG! I understand! NPE was in idName = mTableInfo.getIdName(); It was here because I didn't add Address-class in AA_MODELS
